name: Lint Code

on:
  push:
    branches:
      - development

jobs:
  Lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code and Setup Go enviroment
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.17'

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0

          golangci-lint run 