name: Test

on:
  push:
    branches:
      - development

jobs:
  Test:
    strategy:
      matrix:
        go-version: [1.14.x,1.17.x]
        platforms: [ububtu-latest]

    runs-on: ${{matrix.platforms}}

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go-version}}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        uses: go test ./....